[package]
name = "storm"
version = "0.7.4-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/danylaporte/storm"
publish = false

[dependencies]
async-cell-lock = { git = "https://github.com/danylaporte/async-cell-lock.git" }
attached = { git = "https://github.com/danylaporte/attached.git" }
cache = { git = "https://github.com/danylaporte/cache.git", optional = true }
chrono = { version = "0.4", optional = true, features = ["serde"] }
conv = { version = "0.3", optional = true }
dec19x5 = { git = "https://github.com/danylaporte/dec19x5.git", optional = true }
fxhash = "0.2"
metrics = { version = "0.17", optional = true }
once_cell = "1"
parking_lot = "0.11"
rayon = "1"
serde = { version = "1", features = ["derive"] }
static_init = "1"
storm_derive = { path = "../storm_derive", optional = true }
tiberius = { version = "0.6", optional = true }
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread", "sync"] }
tracing = "0.1"
uuid = { version = "0.8", optional = true, features = ["v4", "serde"] }
vec-map = { git = "https://github.com/danylaporte/vec-map.git", features = ["rayon"] }
version_tag = { git = "https://github.com/danylaporte/version_tag.git" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread", "sync"] }

[features]
default = ["cache", "chrono", "dec19x5", "derive", "uuid"]
derive = ["storm_derive"]
mssql = ["storm_derive/mssql", "tiberius"]
telemetry = ["conv", "metrics", "storm_derive/telemetry"]
