[package]
name = "storm"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/danylaporte/storm"
publish = false

[dependencies]
async-cell-lock = { git = "https://github.com/danylaporte/async-cell-lock.git", branch = "main" }
async-trait = "=0.1.42"
cache = { git = "https://github.com/danylaporte/cache.git", branch = "main", optional = true }
fxhash = "0.2"
metrics = { version = "0.14", optional = true }
once_cell = "1"
storm_derive = { path = "../storm_derive", optional = true }
tiberius = { version = "0.5", optional = true }
tracing = "0.1"
tokio = { version = "1", features = ["parking_lot", "sync"], optional = true }
vec-map = { git = "https://github.com/danylaporte/vec-map.git", branch = "main", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread", "sync"] }

[features]
default = ["cache", "derive", "tokio", "vec-map"]
derive = ["storm_derive"]
metrics_0_14 = ["metrics", "storm_derive/metrics"]
mssql = ["storm_derive/mssql", "tiberius"]
postgres = ["storm_derive/postgres"]
