[package]
name = "storm"
version = "0.4.1"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/danylaporte/storm"
publish = false

[dependencies]
async-cell-lock = { git = "https://github.com/danylaporte/async-cell-lock.git" }
attached = { git = "https://github.com/danylaporte/attached.git" }
cache = { git = "https://github.com/danylaporte/cache.git", optional = true }
fxhash = "0.2"
metrics = { version = "0.16", optional = true }
once_cell = "1"
parking_lot = "0.11"
static_init = "1"
storm_derive = { path = "../storm_derive", optional = true }
tiberius = { version = "0.5", optional = true }
tracing = "0.1"
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread", "sync"] }
vec-map = { git = "https://github.com/danylaporte/vec-map.git" }
version_tag = { git = "https://github.com/danylaporte/version_tag.git" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread", "sync"] }

[features]
default = ["cache", "derive"]
derive = ["storm_derive"]
metrics_0_14 = ["metrics", "storm_derive/metrics"]
mssql = ["storm_derive/mssql", "tiberius"]
