[package]
name = "storm_mssql"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1"
storm = { path = "../storm", features = [] }
tiberius = { version = "0.5.7", features = ["chrono", "sql-browser-tokio"] }
tokio = { version = "1", features = ["io-std", "io-util", "net", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.6", features = ["compat"] }
tracing = "0.1"
tracing-futures = "0.2"

[features]
default = ["cache", "vec-map"]
cache = ["storm/cache"]
vec-map = ["storm/vec-map"]
